# ==============================
# Configuración general del servicio
# ==============================
spring.application.name=auth-service
server.port=8080

# ==============================
# Base de datos
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/tempuroshop?useSSL=false&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=HALO_4_requiem
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false          
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# ==============================
# JWT
# ==============================
jwt.secret=V2x3Rm91U2xRM2lNR1d4T3ZhV2x0dFJ1U1pBM3JYcHQ=
jwt.accessExpiration=900000        
jwt.refreshExpiration=2592000000  

# ==============================
# Logging general
# ==============================
# Limitar logs de librerías externas
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.org.apache.tomcat=WARN

# Logs de tu app
logging.level.com.tempuro.auth=INFO

# Apagar logs de SQL y bind variables
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# Consola más limpia
logging.pattern.console=%-5level - %msg%n
spring.output.ansi.enabled=always


